### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wongsyrone** [wongsyrone/transocks-wong#1]
- [x] figure out resource leak, sockets, fds, etc
- [x] use SIGUSR1  to close all client connections
- [x] use SIGHUP to dump client info
- [x] replace evconnlistener with plain bind/accept & static link to libevent2 git tree
- [x] <del>embed jemalloc</del> not cross compilation friendly
- [x] check v4 mapped v6 addr when checking user input addrs (IN6_IS_ADDR_V4MAPPED)
- [ ] log category
- [x] choose allocator( mimalloc )
- [ ] choose which transparent proxy mechanism to use ( TPROXY/REDIRECT )
